server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.220.128:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 147852
  redis:
    host: 192.168.220.128

mybatis-plus:
  mapper-locations: classpath:mapper/sms/*.xml  # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用分布式id生成技术
