server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.220.128:3306/guli_ums
    username: root
    password: 147852
  redis:
    host: 192.168.220.128
    port: 6379

mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  global-config:
    db-config:
      id-type: auto  # 默认使用分布式id生成技术